### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by thefourtheye**
- remove usage of builtin dict as variable
- remove unused re module

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
@thefourtheye Does removing usage of builtin dict as variable make any affect? or is this for cleaning the code as I like it the way it was. It clearly specifies that it is passing a dict, by that specific mention, makes things easy for beginners. :)

@sutiam Thanks for merging it but let me review the PRs on this repository first, then you can merge. I was thinking no one other than me have this permission. I need to look into the things now. :)

**Comment by dkorolev** [comment]
@tapasweni-pathak use `Teams` to control who has permissions to merge / push into this repo.

**Comment by kratsg** [comment]
:+1: @dkorolev

**Comment by tapaswenipathak** [comment]
@dkorolev Is this what you are talking about? I see it blank. Doesn't this mean that noone has that control or is there any other option to control it?
capture

**Comment by dkorolev** [comment]
Yes. You'll have to `Create new team`, and take it from there. Should be self-explanatory within a few clicks.

**Comment by tapaswenipathak** [comment]
@dkorolev Done. I thought if nothing is there, that means nothing. 

Thanks. :+1:

**Comment by thefourtheye** [comment]
@tapasweni-pathak It serves two purposes. 1. We don't shadow the built-in dict anymore. So we avoid unexpected errors if dict is used elsewhere. 2. Micro optimisation. We assign and return immediately. Instead we can return directly. Saving few OP codes. I'll check if this is already optimised by Python

**Comment by kratsg** [comment]
@thefourtheye that kind of stuff tends to be optimized by python since the dict is a mutable type. Remember everything is passed by reference, so this might be considered overoptimization.

**Comment by thefourtheye** [comment]
@kratsg Both Python 2 and 3 don't optimize that.

``` python
from dis import dis


def b():
    dict = {
        'a': 1
    }
    return dict


dis(b)
print("\n\n\n")


def a():
    return {
        'a': 1
    }

dis(a)
```

**Output**

```
  5           0 BUILD_MAP                1

  6           3 LOAD_CONST               1 (1)
              6 LOAD_CONST               2 ('a')
              9 STORE_MAP           
             10 STORE_FAST               0 (dict)

  8          13 LOAD_FAST                0 (dict)
             16 RETURN_VALUE        




 16           0 BUILD_MAP                1

 17           3 LOAD_CONST               1 (1)
              6 LOAD_CONST               2 ('a')
              9 STORE_MAP           
             10 RETURN_VALUE        
```

**Comment by bfontaine** [comment]
> I was thinking no one other than me have this permission.

@tapasweni-pathak We’re all owners of this organization and have access to all repositories. AFAIK we can’t be owner _without_ access to a given repo.

**Pull request merged**
